trigger:
  - Produccion

variables:
  - group: GitHubSecrets

pool:
  name: 'Default'

steps:
- script: echo 'Iniciando Deploy a Producción...'
  displayName: 'Verificar Agente'

- script: |
    rem Configuramos los usuarios de git
    git config --global user.email "dvegacajas2@gmail.com"
    git config --global user.name "Diego Vega"

    rem Clonamos solo la rama Producción desde GitHub con el token de autenticación
    git clone --single-branch --branch Produccion https://$(GITHUB_TOKEN)@github.com/diegovski02/ProyNaVishe_BACK.git repo-tmp
    cd repo-tmp

    rem Eliminamos el remoto Azure si ya existe
    git remote remove azure || echo "Remote Azure no existe"
    
    rem Agregamos el remoto de Azure
    git remote add azure $(Build.Repository.Uri)

    rem Traemos los últimos cambios de la rama Produccion desde Azure
    git pull azure Produccion --rebase

    rem Hacemos un commit vacío si es necesario
    git commit --allow-empty -m "Actualizando desde Azure a GitHub"

    rem Hacemos el push forzado a GitHub
    git push https://$(GITHUB_TOKEN)@github.com/diegovski02/ProyNaVishe_BACK.git Produccion --force
  displayName: "Push forzado desde Azure a GitHub (Producción limpio)"
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'Produccion'))
