trigger:
  - Produccion

variables:
  - group: GitHubSecrets

pool:
  name: 'Default'

steps:
# Paso 1: Verificar el agente
- script: echo Iniciando Deploy a Producci贸n...
  displayName: 'Verificar Agente'

# Paso 2: Despliegue (personalizable)
# Descomenta y configura si est谩s usando App Service, AKS, etc.
# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: '<NOMBRE-CONEXIN-SERVICIO>'
#     appName: '<NOMBRE-WEBAPP>'
#     package: '$(System.DefaultWorkingDirectory)/**/*.zip'
#   displayName: 'Desplegar a Producci贸n'

# Paso 3: Notificaci贸n final
- script: echo " Despliegue completado en Producci贸n"
  displayName: 'Finalizaci贸n del Deploy'

# Paso 4: Push autom谩tico desde Azure a GitHub (sin errores de conflicto)
- script: |
    git config --global user.email "dvegacajas2@gmail.com"
    git config --global user.name "Diego Vega"

    rem Clona el repositorio con token de GitHub
    git clone https://$(GITHUB_TOKEN)@github.com/diegovski02/ProyNaVishe_BACK.git repo-tmp
    cd repo-tmp

    rem Trae cambios desde GitHub
    git pull origin $(Build.SourceBranchName) --rebase

    rem Conecta con el repo de Azure si no est谩
    git remote add azure $(Build.Repository.Uri) || echo "Remote ya existe"
    git pull azure $(Build.SourceBranchName) --rebase

    rem Empuja la rama de Producci贸n de Azure a GitHub
    git push origin HEAD:$(Build.SourceBranchName)
  displayName: "Push autom谩tico a GitHub desde Azure (Producci贸n)"
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'Produccion'))
