trigger:
  - Produccion

variables:
  - group: GitHubSecrets

pool:
  name: 'Default'

steps:
# Paso 1: Verificar el agente
- script: echo Iniciando Deploy a Producción...
  displayName: 'Verificar Agente'

# Paso 2: Despliegue (personalizable)
# Aquí puedes poner AzureWebApp o cualquier otra acción de despliegue real.
# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: '<NOMBRE-CONEXIÓN-SERVICIO>'
#     appName: '<NOMBRE-WEBAPP>'
#     package: '$(System.DefaultWorkingDirectory)/**/*.zip'
#   displayName: 'Desplegar a Producción'

# Paso 3: Notificación de despliegue
- script: echo "🚀 Despliegue completado en Producción"
  displayName: 'Finalización del Deploy'

# Paso 4: Push automático desde Azure a GitHub (forzado y limpio)
- script: |
    git config --global user.email "dvegacajas2@gmail.com"
    git config --global user.name "Diego Vega"

    rem Clona solo la rama Producción desde Azure
    git clone --single-branch --branch Produccion $(Build.Repository.Uri) repo-tmp
    cd repo-tmp

    rem Agrega el repo GitHub y fuerza el push
    git remote add github https://$(GITHUB_TOKEN)@github.com/diegovski02/ProyNaVishe_BACK.git
    git push github Produccion --force
  displayName: "Push forzado desde Azure a GitHub (Producción limpio)"
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'Produccion'))

