trigger:
  - Produccion

variables:
  - group: GitHubSecrets

pool:
  name: 'Default'

steps:

# Paso 1: Verificar que el agente est茅 disponible
- script: echo Iniciando Deploy a Producci贸n...
  displayName: 'Verificar Agente'

# Paso 2 (opcional): Despliegue del sistema (ajustar seg煤n infraestructura)
# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: '<NOMBRE-CONEXIN-SERVICIO>'
#     appName: '<NOMBRE-WEBAPP>'
#     package: '$(System.DefaultWorkingDirectory)/**/*.zip'
#   displayName: 'Desplegar a Producci贸n'

# Paso 3: Mensaje de despliegue exitoso
- script: echo " Despliegue completado en Producci贸n"
  displayName: 'Finalizaci贸n del Deploy'

# Paso 4: Push autom谩tico de Azure a GitHub (sin sobrescribir ramas)
- script: |
    git config --global user.email "dvegacajas2@gmail.com"
    git config --global user.name "Diego Vega"

    rem Clona el repositorio desde GitHub usando token
    git clone https://$(GITHUB_TOKEN)@github.com/diegovski02/ProyNaVishe_BACK.git repo-tmp
    cd repo-tmp

    rem Trae los 煤ltimos cambios de la rama Produccion de GitHub
    git pull origin Produccion --rebase

    rem Conecta con el repositorio Azure (si no existe)
    git remote add azure $(Build.Repository.Uri) || echo "Remoto ya existe"
    git pull azure Produccion --rebase

    rem Empuja solo la rama Produccion desde Azure a GitHub
    git push origin HEAD:Produccion
  displayName: "Push autom谩tico a GitHub desde Azure (Producci贸n sin conflictos)"
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'Produccion'))
