trigger:
  - Produccion

variables:
  - group: GitHubSecrets

pool:
  name: 'Default'

steps:
# Paso 1: Verificar el agente
- script: echo Iniciando Deploy a Producción...
  displayName: 'Verificar Agente'

# Paso 2: Despliegue (personalizable)
# Aquí puedes poner AzureWebApp o cualquier otra acción de despliegue real.
# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: '<NOMBRE-CONEXIÓN-SERVICIO>'
#     appName: '<NOMBRE-WEBAPP>'
#     package: '$(System.DefaultWorkingDirectory)/**/*.zip'
#   displayName: 'Desplegar a Producción'

# Paso 3: Notificación de despliegue
- script: echo "🚀 Despliegue completado en Producción"
  displayName: 'Finalización del Deploy'

# Paso 4: Push automático desde Azure a GitHub (Producción limpio y seguro)
- script: |
    echo "🔁 Configurando Git..."
    git config --global user.email "dvegacajas2@gmail.com"
    git config --global user.name "Diego Vega"

    echo "📦 Clonando solo la rama Produccion desde GitHub..."
    git clone --branch Produccion https://$(GITHUB_TOKEN)@github.com/diegovski02/ProyNaVishe_BACK.git repo-tmp
    cd repo-tmp

    echo "🔄 Agregando Azure como remoto (si no existe)..."
    git remote add azure $(Build.Repository.Uri) || echo "Remoto Azure ya existe"

    echo "📥 Haciendo pull desde Azure (rama Produccion)..."
    git pull azure Produccion --rebase

    echo "🚀 Haciendo push forzado a GitHub (Produccion)..."
    git push origin Produccion --force
  displayName: "Push forzado desde Azure a GitHub (Producción limpio)"
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'Produccion'))


