trigger:
  - Produccion

variables:
  - group: GitHubSecrets
  - group: AZURE_TOKEN

pool:
  name: 'Default'

steps:
# Paso 1: Verificar el agente
- script: echo 'Iniciando Deploy a Producción...'
  displayName: 'Verificar Agente'

# Paso 2: Verificación de las variables de los tokens
- script: |
    echo "Verificando AZURE_TOKEN..."
    echo $(AZURE_TOKEN)  # Esto imprimirá el valor del AZURE_TOKEN
  displayName: 'Verificar AZURE_TOKEN'

- script: |
    echo "Verificando GITHUB_TOKEN..."
    echo $(GITHUB_TOKEN)  # Esto imprimirá el valor del GITHUB_TOKEN
  displayName: 'Verificar GITHUB_TOKEN'

# Paso 3: Empaquetar la aplicación en un archivo .zip
- script: |
    echo "Empaquetando la aplicación..."
    # Usamos el comando de PowerShell o bash para crear el archivo zip
    powershell Compress-Archive -Path $(Build.SourcesDirectory)\* -DestinationPath $(Build.ArtifactStagingDirectory)\NaVisheWebApp.zip
  displayName: 'Empaquetar la aplicación'

# Paso 4: Despliegue a Producción (personalizable)
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureForStudentsConnection'
    appName: 'NaVisheWebApp'
    package: '$(Build.ArtifactStagingDirectory)/NaVisheWebApp.zip'
    displayName: 'Desplegar a Producción'

# Paso 5: Notificación de despliegue
- script: echo "🚀 Despliegue completado en Producción"
  displayName: 'Finalización del Deploy'

# Paso 6: Push automático desde Azure a GitHub (Reemplazo completo)
- script: |
    rem Configuramos los usuarios de git
    git config --global user.email "dvegacajas2@gmail.com"
    git config --global user.name "Diego Vega"

    rem Clonamos solo la rama Producción desde GitHub con el token de autenticación
    git clone --single-branch --branch Produccion https://$(GITHUB_TOKEN)@github.com/diegovski02/ProyNaVishe_BACK.git repo-tmp
    cd repo-tmp

    rem Eliminamos el remoto Azure si ya existe
    git remote remove azure || echo "Remote Azure no existe"

    rem Agregamos el remoto de Azure con el token de Azure
    git remote add azure https://$(AZURE_TOKEN)@dev.azure.com/diegovega2/ProyNaVishe/_git/ProyNaVishe_BACK.git

    rem Traemos los últimos cambios de la rama Produccion desde Azure
    git fetch azure Produccion

    rem Reseteamos la rama Produccion de GitHub para que sea idéntica a la de Azure
    git reset --hard azure/Produccion

    rem Hacemos el push forzado para sobrescribir la rama en GitHub con lo que tiene Azure
    git push https://$(GITHUB_TOKEN)@github.com/diegovski02/ProyNaVishe_BACK.git Produccion --force
  displayName: "Push desde Azure a GitHub (Producción limpio)"
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'Produccion'))
