trigger:
- Pruebas

variables:
- group: GitHubSecrets

pool:
  name: 'Default'

steps:
- script: echo 'Verificando agente disponible...'
  displayName: 'Verificar Agente'


- script: |
    git config --global user.email "dvegacajas2@gmail.com"
    git config --global user.name "Diego Vega"

    git clone --mirror $(Build.Repository.Uri) repo-tmp
    cd repo-tmp

    git remote remove github || true
    git remote add github "https://$(GITHUB_TOKEN)@github.com/diegovski02/ProyNaVishe_BACK.git"

    # Paso opcional para verificar acceso con el token
    git ls-remote "https://$(GITHUB_TOKEN)@github.com/diegovski02/ProyNaVishe_BACK.git"

    git push github --mirror
  displayName: 'Push automático a GitHub desde Azure'
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'Pruebas'))

