trigger:
  - Pruebas

variables:
  - group: GitHubSecrets

pool:
  name: 'Default'

steps:
- script: |
    echo 'Verificando agente disponible...'
    git config --global user.email "dvegacajas2@gmail.com"
    git config --global user.name "Diego Vega"

    # Clona el repositorio GitHub directamente con el token
    git clone https://$(GITHUB_TOKEN)@github.com/diegovski02/ProyNaVishe_BACK.git repo-tmp
    cd repo-tmp

    # Asegura que tienes lo último del branch actual
    git pull origin $(Build.SourceBranchName)

    # Agrega el repositorio de Azure (si no existe) y sincroniza
    git remote add azure $(Build.Repository.Uri) || true
    git pull azure $(Build.SourceBranchName)

    # Push a GitHub
    git push origin HEAD:$(Build.SourceBranchName)
  displayName: 'Push automático desde Azure a GitHub'
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'Pruebas'))

