trigger:
- Test1

variables:
- group: GitHubSecrets

pool:
  name: 'Default'

steps:
# Paso 1: Verificar el agente
- script: echo 'Verificando agente disponible...'
  displayName: 'Verificar Agente'

# Paso 2: Validar código y pruebas con Maven
#- script: mvn clean verify
#  displayName: 'Validar código y ejecutar pruebas'
#  workingDirectory: '$(System.DefaultWorkingDirectory)'

# Paso 3: Publicar resultados de pruebas
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '$(System.DefaultWorkingDirectory)/target/surefire-reports/TEST-*.xml'
    testRunTitle: 'Resultados de Pruebas Backend'

# Paso 4: Análisis de Seguridad con Microsoft Security DevOps
- task: MicrosoftSecurityDevOps@1
  displayName: 'Análisis de Seguridad DevSecOps'

# Paso 5: Push automático a GitHub desde Azure (solo si está en rama Test1)
- script: |
    git config --global user.email "dvegacajas2@gmail.com"
    git config --global user.name "Diego Vega"

    git clone --mirror $(Build.Repository.Uri) repo-tmp
    cd repo-tmp

    git remote add github https://$(GITHUB_TOKEN):x-oauth-basic@github.com/diegovski02/ProyNaVishe_BACK.git
    git push github --mirror
  displayName: "Push automático a GitHub desde Azure"
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'Pruebas'))