trigger:
- main

variables:
  - group: GitHubSecrets

pool:
  name: 'Default'

steps:
- script: echo 'Verificando agente disponible...'
  displayName: 'Verificar Agente'

- script: mvn clean verify
  displayName: 'Validar código y ejecutar pruebas'
  workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '$(System.DefaultWorkingDirectory)/target/surefire-reports/TEST-*.xml'
    testRunTitle: 'Resultados de Pruebas Backend'

- script: |
    git config --global user.email "dvegacajas2@gmail.com"
    git config --global user.name "Diego Vega"

    git clone --mirror $(Build.Repository.Uri) repo-tmp
    cd repo-tmp

    git remote add github https://$(GITHUB_TOKEN):x-oauth-basic@github.com/diegovski02/ProyNaVishe_BACK.git
    git push github --mirror
  displayName: "Push automático a GitHub desde Azure"
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))